baseURL = 'https://go-api--polimi-electronics.netlify.app/'
languageCode = 'en-us'
title = 'Electronics engineering at Polimi'
theme = 'hugo-bearblog-patch'
disableKinds = ["taxonomy"]

enableEmoji = true

[params]
favicon = "favicon.ico"
